### ISSUE TITLE
Stuck at Connecting Server

### ISSUE THREAD

**Issue by Lemocuber** [CrazorTheCat/BSDS-V43#5]
When I open the game, it stucks at "connecting server..."
I'm sure there is no problem with the ip or port address.

The server system used is Ubuntu 18, and I ran the program using "python3 Core.py"
The server side says "Listening for new connection..." and nothing suggesting there is a connection request
By the way, I used exteral ip to connect, since it's a cloud server

Hmm, I'm just wondering if it's the ubuntu python environment that causes the problem.
😥

**Comment by CrazorTheCat** [comment]
hmm i have no idea sorry
